var perfUrl = {
    'validateSession'  : urlPrefix+'user/validateSession',
    'logout' : urlPrefix+'utils/logout',
    'getVersion' : urlPrefix+'utils/version',
    'updatePwd'  : urlPrefix+'user/updatePwd',
    'resetPassword': urlPrefix+'user/resetPassword?employeePk=',
    'loadAllEmployees'  : urlPrefix+'employee/loadAllEmployees',
    'loadEmployeesBySupervisor' : urlPrefix+'employee/loadEmployeesBySupervisor/{limit}/{year}',
    'loadEmployees'  : urlPrefix+'employee/loadEmployees',
    'loadAllEmployeeByNames'  : urlPrefix+'employee/loadAllEmployeeByNames',
    'loadAllEmployeeNamesByDate' : urlPrefix+'employee/loadAllEmployeeNamesByDate/{fromDate}/{toDate}',
    'loadEmployee'     : urlPrefix+'employee/loadEmployee',
    'loadUserNameViewById' : urlPrefix+'employee/loadUserNameViewById?employeeId=',
    'loadEmployeeById' : urlPrefix+'employee/loadEmployeeById?employeeId=',
    'loadByEmployeeById' : urlPrefix+'employee/loadByEmployeeById?employeeId=',
    'updateEmployee'   : urlPrefix+'employee/updateEmployee',
    'generateCrendentials'   : urlPrefix+'employee/generateCrendentials?employeeId=',
    'addEmployee'      : urlPrefix+'employee/addEmployee',
    'loadEmployeeByDesHistory' : urlPrefix+'employee/loadEmployeeByDesHistory/{fromDate}/{toDate}/{designation}',
    'loadDesignations' : urlPrefix+'designation/loadDesignations',
    'loadDesignationById' : urlPrefix+'designation/loadDesignationById?id=',
    'addDesignation'   : urlPrefix+'designation/addDesignation',
    'updateDesignation': urlPrefix+'designation/updateDesignation',
    'deleteDesignation' : urlPrefix+'designation/deleteDesignation',
    'loadProjects' : urlPrefix+'projects/loadProjects',
    'addProject'   : urlPrefix+'projects/addProject',
    'updateProject': urlPrefix+'projects/updateProject',
    'deleteProject': urlPrefix+'projects/deleteProject',
    'loadProjectById' : urlPrefix+'projects/loadProjectById?projectPk=',
    'loadProjectMembersByProjectId' : urlPrefix+'projectmembers/loadProjectMembersByProjectId?projectId=',
    'loadAllProjectMembers' : urlPrefix+'projectmembers/loadAllProjectMembers',
    'loadMyProjects' : urlPrefix+'projectmembers/loadMyProjects',
    'loadProjectMemberById' : urlPrefix+'projectmembers/loadProjectMemberById?projectMemberId=',
    'saveProjectMember' : urlPrefix+'projectmembers/saveProjectMember',
    'updateProjectMember' : urlPrefix+'projectmembers/updateProjectMember',
    'deleteProjectMember' : urlPrefix+'projectmembers/deleteProjectMember',
    'importPto' : urlPrefix+'leave/fetchExcel',
    'importEbsPto' : urlPrefix+'ebsleave/uploadEbsLeaves',
    'loadEbsLeaveReport' : urlPrefix+'ebsleave/loadEbsLeaveReport',
    'uploadLeaveBal' : urlPrefix+'leave/uploadOpeningBalance',
    'importWfhCalInfoFromIcs' : urlPrefix+'leave/importWfhCalInfoFromIcs',
    'importOfficeEntry' : urlPrefix+'leave/importOfficeEntry',
    'carryLeaves' : urlPrefix+'leave/carryLeaves/{year}',
    'getCarryLeaves' : urlPrefix+'leave/getCarryLeaves/{year}',
    'applyLeave' : urlPrefix+'leave/applyLeave',
    'loadLeavesByYear' : urlPrefix+'leave/loadLeavesByYear/{leaveType}/{calYear}',
    'loadLeavesByMonth' : urlPrefix+'leave/loadLeavesByMonth/{leaveType}/{calYear}/{calMonth}',
    'updateLeave' : urlPrefix+'leave/updateLeave',
    'deleteLeave' : urlPrefix+'leave/deleteLeave',
    'loadLeaveById' : urlPrefix+'leave/loadLeaveById?leaveId=',
    'loadMyLeaves' : urlPrefix+'leave/loadMyLeaves/{leaveType}/{calYear}',
    'getLeaveBalance' : urlPrefix+'leave/getLeaveBalance/{leaveType}/{calYear}/{calMonth}',
    'getEmpLeaveBalance' : urlPrefix+'leave/getEmpLeaveBalance/{calYear}',
    'getLeaveBalanceByMonth' : urlPrefix+'leave/getLeaveBalanceByMonth/{leaveType}/{calYear}',
    'getLeaveBalanceByType': urlPrefix+'leave/getLeaveBalanceByType/{leaveType}/{calYear}',
    'loadLeaveReport': urlPrefix+'leave/loadLeaveReport',
    'loadAllLeaveReport': urlPrefix+'leave/loadAllLeaveReport',
    'loadNotificationCount' : urlPrefix+'notification/loadNotificationCount',
    'reportsLoadBySbu' : urlPrefix+'reportJobTitle/loadBySbu/{fromDate}/{toDate}/{sbu}/{designation}',
    'loadRoles' : urlPrefix+'roles/loadRoles',
    'loadRolesById' : urlPrefix+'roles/loadRolesById?id=',
    'addRoles'   : urlPrefix+'roles/addRoles',
    'updateRoles': urlPrefix+'roles/updateRoles',
    'deleteRoles' : urlPrefix+'roles/deleteRoles',
    'loadComponents' : urlPrefix+'components/loadComponents',
    'loadComponentsById' : urlPrefix+'components/loadComponentsById?id=',
    'addComponent'   : urlPrefix+'components/addComponent',
    'updateComponent': urlPrefix+'components/updateComponent',
    'deleteComponent' : urlPrefix+'components/deleteComponent',
    'saveEmpRoles' : urlPrefix+'emproles/saveEmpRoles',
    'loadNonEmpByRoles' : urlPrefix+'emproles/loadNonEmpByRoles?roleId=',
    'loadEmpByRoles' : urlPrefix+'emproles/loadEmpByRoles?roleId=',
    'loadEmpRoles' : urlPrefix+'emproles/loadEmpRoles',
    'loadRolesByEmpId': urlPrefix+'emproles/loadRolesByEmpId',
    'loadHolidays' : urlPrefix+'holidays/loadHolidays',
    'addHoliday'   : urlPrefix+'holidays/addHoliday',
    'updateHoliday': urlPrefix+'holidays/updateHoliday',
    'deleteHoliday' : urlPrefix+'holidays/deleteHoliday',
    'getHolidaysByYear' : urlPrefix+'holidays/getHolidaysByYear?year=',
    'loadByeOutByYear' : urlPrefix+'empleavemaintenance/loadByeOutByYear?year=',
    'saveLeaveMaintanance' : urlPrefix+'empleavemaintenance/saveLeaveMaintanance',
    'updateLeaveMaintanance' : urlPrefix+'empleavemaintenance/updateLeaveMaintanance',
    'loadNotificationByType': urlPrefix+'notification/loadNotificationByType/{type}/{status}',
    'loadNotificationMsgs': urlPrefix+'notification/loadNotificationMsgs',
    'approveRejectNotification' : urlPrefix+'notification/approveRejectNotification/{id}/{status}',
    'markReadNotification' : urlPrefix+'notification/markReadNotification/{id}',
    'delegateNotification' : urlPrefix+'notification/delegateNotification/{id}/{empId}',
    'addTicket'   : urlPrefix+'tickets/addTicket',
    'updateTicket': urlPrefix+'tickets/updateTicket',
    'deleteTicket' : urlPrefix+'tickets/deleteTicket',
    'loadTickets' : urlPrefix+'tickets/loadTickets',
    'loadTicketsById' : urlPrefix+'tickets/loadTicketsById',
    'loadTicketByTicketId' : urlPrefix+'tickets/loadTicketByTicketId',
    'loadAssignedTickets' : urlPrefix+'tickets/loadAssignedTickets',
    'deleteAttachment' :  urlPrefix+'tickets/deleteAttachment',
    'deleteComment' :  urlPrefix+'tickets/deleteComment',
    'loadTicketsReport':  urlPrefix+'tickets/loadTicketsReport'
};